version: '3'
services:
  app:
    build: .
    # Tag image as appropriate for app distribution
    # image: fsgssg/pharos:latest
    links:
      - redis
      - db
    volumes:
      - app_data:/tmp
      - ./docker/db/data:/var/lib/postgresql/data_import
      - .:/usr/src/app
    ports:
      - "80:3000"
      - "443:443"
    tty: true
    stdin_open: true
    command: /bin/bash -c ./docker/rails/bin/start-dev.sh
    entrypoint: ./docker/rails/bin/entrypoint.sh
    environment:
      AWS_ACCESS_KEY_ID: ${PHAROS_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${PHAROS_AWS_SECRET_ACCESS_KEY}
      POSTMARK_API_KEY: ''
      RACK_ENV: production
      RAILS_ENV: production
      REDIS_URL: redis
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SIDEKIQ_WEB_PASSWORD: password
      SIDEKIQ_WEB_USERNAME: username

  redis:
    image: redis:4.0.9-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  sidekiq:
    build: .
    links:
      - db
      - redis
    tty: true
    stdin_open: true
    command: sidekiq -C config/sidekiq.yml
    entrypoint: ./docker/rails/bin/entrypoint.sh
    environment:
      AWS_ACCESS_KEY_ID: ${PHAROS_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${PHAROS_AWS_SECRET_ACCESS_KEY}
      POSTMARK_API_KEY: ''
      RACK_ENV: production
      RAILS_ENV: production
      REDIS_URL: redis
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SIDEKIQ_WEB_PASSWORD: password
      SIDEKIQ_WEB_USERNAME: username

  db:
    image: postgres:9.6.8
    #build: ./docker/db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  app_data:
  db_data:
  redis:
